### ISSUE TITLE
DNS address support

### ISSUE THREAD

**Issue by rshirochenko** [exonum/exonum#1011]
Exonum version: v.0.9.3

1) The DNS addresses do not work with the config generation commands (generate-config, finalize, run).
E.g. this command will fail
`exonum-timestamping generate-config example/common.toml  example/pub_1.toml example/sec_1.toml --peer-address www.google.com
`
2) The node does not start and fail if DNS address does not exist for the start moment. The case:
One of the peer DNS address is example1, the CI configured to activate DNS address after process starting. As the process fails on the DNS check, it impossible to realize this scenario.

**Comment by ivan-ochc** [comment]
Such functionality wasn't released in v0.9.3.
Release 0.10 will contain PR https://github.com/exonum/exonum/pull/942 which fix your issue.
