### ISSUE TITLE
Accessing shared functionality across services

### ISSUE THREAD

**Issue by zakum1** [exonum/exonum#1025]
Hello exonum developers, thank you for  this great project!

In my application, I have some interaction between services, in which I cache data for performance reasons. I would like the API's and transaction verification to be able to access this stateful cache.

In the canonical implementation of services, the API's only have access to the ServiceApiState, which provides access to the blockchain.

Is there a canonical way in which I can make my own stateful objects available to API handlers and transaction verification implementations. 

I could make this available through global state, but wanted to avoid that if other applications have solved this elegantly.

Many thanks

**Comment by aleksuss** [comment]
@zakum1 For example you can create something like `Arc<Mutex<Cache>>` before a node building and then pass a reference to the `State` into service's constructor. Where `Cache` it's your stateful cache.

**Comment by zakum1** [comment]
Thanks
