### ISSUE TITLE
failed to run exonum_libsodium-sys v0.0.20

### ISSUE THREAD

**Issue by rakhmanu** [exonum/exonum#1029]
Hi, 
I am trying to run  advanced- cryptocurrency through the command cargo build, however there is an error such as failed to run exonum_libsodium-sys v0.0.20. I have installed cmake and all of the stuffs that could be found on the internet. Has anybody the same problem and please share with the solution if smn figured out
Thanks 
Appreciate your time

**Comment by aleksuss** [comment]
Hello @rakhmanu. What's OS do you use for running cryptocurrency-advanced ?

**Comment by rakhmanu** [comment]
Ubuntu

понедельник, 5 ноября 2018 г. пользователь Oleksandr Anyshchenko написал:

**Comment by vitvakatu** [comment]
@rakhmanu Hello. Sorry for a long response. Is this issue still valid for you? If yes, please provide the following info:
1. Full output of compile log (after running cargo build)
2. You Rust environment (use `rustup show` command)
3. Your Exonum version (are you using github master or some other version?)

Thanks

**Comment by rakhmanu** [comment]
No I solved it thanks

среда, 21 ноября 2018 г. пользователь Ilya Bogdanov написал:

**Comment by aleksuss** [comment]
@rakhmanu could you please close the issue ?

**Comment by rakhmanu** [comment]
Ок

среда, 21 ноября 2018 г. пользователь Oleksandr Anyshchenko написал:
