### ISSUE TITLE
Cannot propose new config

### ISSUE THREAD

**Issue by Mikelle** [exonum/exonum#1107]
Hello, I have a question. How can I propose new configuration? I'm using this tutorial (https://github.com/exonum/exonum/blob/master/services/configuration/doc/testnet-api-tutorial.md), but when I sending postpropose request with new config nothing is happening and even I didn't have any responses from request. How can I understand what is wrong with request?
![screenshot_2018-12-18_14-43-14](https://user-images.githubusercontent.com/5672938/50155168-6578ff80-02dc-11e9-83d6-961d6fbc5482.png)
![screenshot_2018-12-18_14-43-43](https://user-images.githubusercontent.com/5672938/50155173-67db5980-02dc-11e9-9020-282a67d55e93.png)
![screenshot_2018-12-18_14-44-05](https://user-images.githubusercontent.com/5672938/50155178-69a51d00-02dc-11e9-9108-e91ed500ac53.png)
![screenshot_2018-12-18_14-47-56](https://user-images.githubusercontent.com/5672938/50155179-6ad64a00-02dc-11e9-83ae-5fede9b31de2.png)

**Comment by aleksuss** [comment]
@Mikelle hello. Thank you for your interest. What's a version of Exonum do you use ?

**Comment by Mikelle** [comment]
I used master branch and 0-9-5-release

**Comment by aleksuss** [comment]
Have you tried to add `-X POST` parameter ?

**Comment by Mikelle** [comment]
Yes, same result.

**Comment by Mikelle** [comment]
Yes, I used private api port. What confuses me is that there are no error messages at all.
![screenshot_2018-12-18_17-32-37](https://user-images.githubusercontent.com/5672938/50160697-ff47a900-02ea-11e9-821b-c71ee702c700.png)

**Comment by aleksuss** [comment]
I know it is strange but actually it is ok if no messages at all when wrong request. Could you try this flow in dev mode ? 
`$ RUST_LOG=info configuration run-dev`

**Comment by Mikelle** [comment]
@aleksuss Thank you, finally I can read error logs, problem was with json file.
