### ISSUE TITLE
Creation of disturbed network.

### ISSUE THREAD

**Issue by Mikelle** [exonum/exonum#1108]
Hello, how can I create network with separate machines? Do you have any guide? I'm trying to connect with different addresses set up, but nothing works. Nodes see each other, but not starting to mine blocks. On one local machine everything works fine.

**Comment by aleksuss** [comment]
@Mikelle hello. Could you provide some log files please ?

**Comment by ivan-ochc** [comment]
@Mikelle, hi. Did you set correct host for each peer-address? Could you please provide more details: configs, logs, etc.?
I configured 2 nodes on local machine and 2 - on remote - network has started as expected.
