### ISSUE TITLE
Exonum Timestamping

### ISSUE THREAD

**Issue by SabrinaOmerefendic** [exonum/exonum#1113]
Trying to setup timestamping for Exonum, but unfortunately I been getting this error, "exonum-timestamping: command not found". Any idea how to fix it?
![screenshot from 2018-12-28 13-26-01](https://user-images.githubusercontent.com/44608411/50515367-7d067400-0aa4-11e9-89ad-3020aea69404.png)

**Comment by aleksuss** [comment]
Try to execute this command: 
`$ export PATH=$PATH:$HOME/.cargo/bin`

**Comment by SabrinaOmerefendic** [comment]
Thank you, that worked!
