### ISSUE TITLE
Cannot build Exonum - Cargo Test Failure

### ISSUE THREAD

**Issue by bricknevada** [exonum/exonum#1224]
Getting error when running on clean server with latest git:

 __cargo test --manifest-path exonum/Cargo.toml__

Complete error as follows:
Updating crates.io index
error: failed to select a version for `lazy_static`.                                                  
    ... required by package `criterion v0.2.7`
    ... which is depended on by `exonum v0.10.1 (/home/ubuntu/projects/exonum/exonum)`
    ... which is depended on by `exonum-testkit v0.10.0 (/home/ubuntu/projects/exonum/testkit)`
    ... which is depended on by `exonum-time v0.10.0 (/home/ubuntu/projects/exonum/services/time)`
    ... which is depended on by `exonum-timestamping v0.0.0 (/home/ubuntu/projects/exonum/examples/timestamping/backend)`
versions that meet the requirements `~1.1` are: 1.1.0

all possible versions conflict with previously selected packages.

  previously selected package `lazy_static v1.2.0`
    ... which is depended on by `ring v0.13.5`
    ... which is depended on by `cookie v0.11.0`
    ... which is depended on by `actix-web v0.7.17`
    ... which is depended on by `exonum-testkit v0.10.0 (/home/ubuntu/projects/exonum/testkit)`
    ... which is depended on by `exonum-time v0.10.0 (/home/ubuntu/projects/exonum/services/time)`
    ... which is depended on by `exonum-timestamping v0.0.0 (/home/ubuntu/projects/exonum/examples/timestamping/backend)`

failed to select a version for `lazy_static` which could resolve this conflict

**Comment by skjortan23** [comment]
I am getting the same error trying to build both master and branch '0-10-1-release'.

**Comment by skjortan23** [comment]
I managed to get it all to build by applying the following https://github.com/exonum/exonum/pull/1225/files

**Comment by bricknevada** [comment]
Thank you @skjortan23...that resolved the lazy_static.
