### ISSUE TITLE
failed to run custom build command for `exonum v0.10.2

### ISSUE THREAD

**Issue by SabrinaOmerefendic** [exonum/exonum#1231]
Hello, I noticed that there was a never version of Exonum up, and I was using exonum-0.9.5, and wanted to upgrade to exonum-0.10.2. But am having this error.
![screenshot from 2019-01-18 10-59-34](https://user-images.githubusercontent.com/44608411/51379802-8f5a5780-1b10-11e9-93e8-e6e2a31e606c.png)

**Comment by aleksuss** [comment]
@SabrinaOmerefendic hello. Try execute such command and try againg:
```bash
sudo apt install protobuf-compiler
```

**Comment by SabrinaOmerefendic** [comment]
![screenshot from 2019-01-18 11-12-13](https://user-images.githubusercontent.com/44608411/51380392-f593aa00-1b11-11e9-86fb-230952914191.png)
Still having an error

**Comment by aleksuss** [comment]
Probably you have installed old version of protobuf compiler. What's a version of OS do you use ?

**Comment by SabrinaOmerefendic** [comment]
@aleksuss linux ubuntu 16.04

**Comment by aleksuss** [comment]
Than try this:
```bash
sudo apt-get remove protobuf-compiler
sudo add-apt-repository ppa:maarten-fonville/protobuf
sudo apt-get update
sudo apt-get install protobuf-compiler
```

**Comment by SabrinaOmerefendic** [comment]
@aleksuss still same error :/

**Comment by aleksuss** [comment]
Run
```bash
sudo apt install libprotobuf-dev
```

**Comment by SabrinaOmerefendic** [comment]
Thank you that worked! I am closing the issue now
