### ISSUE TITLE
Timestamping exonum-0.10.2

### ISSUE THREAD

**Issue by SabrinaOmerefendic** [exonum/exonum#1233]
This is more of a question, will it cause any issue to the program it self. I followed previous advice I was given for the timestamping. It is working, but after I followed the tutorial, and the command "npm run build" has an error, but I tried still to run the 4 nodes and command "npm start ..." on designated port. And the timestamping demo is working. What could be the solution to the error for npm run build.
![screenshot from 2019-01-21 12-01-32](https://user-images.githubusercontent.com/44608411/51470485-51f60400-1d74-11e9-9920-947d637da1ec.png)

**Comment by SabrinaOmerefendic** [comment]
Log: 
0 info it worked if it ends with ok
1 verbose cli [ '/home/sabe/.nvm/versions/node/v11.6.0/bin/node',
1 verbose cli   '/home/sabe/.nvm/versions/node/v11.6.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.5.0-next.0
3 info using node@v11.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle timestamping-demo@1.0.0~prebuild: timestamping-demo@1.0.0
6 info lifecycle timestamping-demo@1.0.0~build: timestamping-demo@1.0.0
7 verbose lifecycle timestamping-demo@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle timestamping-demo@1.0.0~build: PATH: /home/sabe/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/sabe/Exonum/exonum-0.10.2/examples/timestamping/frontend/node_modules/.bin:/home/sabe/.nvm/versions/node/v11.6.0/bin:/home/sabe/bin:/home/sabe/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle timestamping-demo@1.0.0~build: CWD: /home/sabe/Exonum/exonum-0.10.2/examples/timestamping/frontend
10 silly lifecycle timestamping-demo@1.0.0~build: Args: [ '-c',
10 silly lifecycle   'npm run proto && npm run lint && npm run compile && npm run test' ]
11 silly lifecycle timestamping-demo@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle timestamping-demo@1.0.0~build: Failed to exec build script
13 verbose stack Error: timestamping-demo@1.0.0 build: `npm run proto && npm run lint && npm run compile && npm run test`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/sabe/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:188:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/sabe/.nvm/versions/node/v11.6.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:188:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid timestamping-demo@1.0.0
15 verbose cwd /home/sabe/Exonum/exonum-0.10.2/examples/timestamping/frontend
16 verbose Linux 4.15.0-43-generic
17 verbose argv "/home/sabe/.nvm/versions/node/v11.6.0/bin/node" "/home/sabe/.nvm/versions/node/v11.6.0/bin/npm" "run" "build"
18 verbose node v11.6.0
19 verbose npm  v6.5.0-next.0
20 error code ELIFECYCLE
21 error errno 1
22 error timestamping-demo@1.0.0 build: `npm run proto && npm run lint && npm run compile && npm run test`
22 error Exit status 1
23 error Failed at the timestamping-demo@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ivan-ochc** [comment]
@SabrinaOmerefendic, it should work. Try to remove `node_modules` folder inside `frontend` and execute again:
```
npm install
npm run build
```

**Comment by SabrinaOmerefendic** [comment]
It worked. Thank you a lot!
