### ISSUE TITLE
Build error in flate2::read::GzDecoder

### ISSUE THREAD

**Issue by orthecreedence** [exonum/exonum#1244]
Hello! I'm trying to build exonum `v0.10.3` (rust v1.31.0) and having issues with the build script in `exonum_libsodium-sys`:

```
   Compiling exonum_librocksdb-sys v0.5.4
   Compiling exonum_libsodium-sys v0.0.20
error[E0599]: no method named `unwrap` found for type `flate2::read::GzDecoder<std::fs::File>` in the current scope
   --> C:\Users\andrew\.cargo\registry\src\github.com-1ecc6299db9ec823\exonum_libsodium-sys-0.0.20\buil
d.rs:434:49
    |
434 |     let gz_decoder = GzDecoder::new(gz_archive).unwrap();
    |                                                 ^^^^^^

error: aborting due to previous error
```

It looks like libsodium-sys is using flate2 version 1.0.1, which doesn't wrap the result of GzDecoder::new in a result, so it doesn't need an unwrap. I wasn't sure whether to post this in exonum-sodium, so I defaulted to posting here, hope that's ok.

Thank you!

**Comment by vitvakatu** [comment]
Thank you for creating an issue, we will investigate

**Comment by ivan-ochc** [comment]
@orthecreedence, I tried to reproduce your issue, but I didn't have any problem with `exonum_libsodium-sys` compilation. Try `cargo clean && cargo update` before compilation.

**Comment by orthecreedence** [comment]
Ok, I ran those commands (both successful) and am having the same issue.

Here's the code block it looks like it's running:

```rust
#[cfg(all(windows, not(target_env = "msvc"), not(feature = "use-installed-libsodium")))]
fn main() {
    use flate2::read::GzDecoder;
    use std::fs::{self, File};
    use std::path::Path;
    use tar::Archive;

    check_powershell_version();

    // Download gz tarball
    let install_dir = get_install_dir();
    let lib_install_dir = Path::new(&install_dir).join("lib");
    fs::create_dir_all(&lib_install_dir).unwrap();
    let gz_path = download_compressed_file();

    // Unpack the tarball
    let gz_archive = File::open(&gz_path).unwrap();
    let gz_decoder = GzDecoder::new(gz_archive).unwrap();    // <----- problem line here
    let mut archive = Archive::new(gz_decoder);
```

Looks like it's a windows-specific build problem (sorry, I forgot to mention that). I also see a feature for `use-installed-libsodium` there...I do already have libsodium installed so I'll give that a shot as well.

**Comment by orthecreedence** [comment]
Sorry, I'm having a hard time figuring out how to even pass the `use-installed-libsodium` feature from my crate down through exonum. Any tips on how I would do this? It doesn't look like it's exposed in the features of exonum's Cargo.toml so I'm not sure how to have it go down the tree to exonum_libsodium-sys. Thanks!

**Comment by orthecreedence** [comment]
I "fixed" this by downloading everything locally and pointing all the Cargo.toml references to a local `exonum_sodium` folder where I edited `libsodium-sys/build.rs` to just output the locations to my local installation of libsodium...seems to work. That said, I think it'd be great to expose a feature in `exonum` that lets you use a local version of libsodium (instead of downloading/compiling). sodiumoxide already does this if you set the env:
```
export SODIUM_LIB_DIR=c:/lib/lib
export SODIUM_SHARED=0
```
so it would be great if there was a simple build option that allowed this (and could be enabled as a feature when grabbing exonum via crates.io).
