### ISSUE TITLE
exonum_libsodium-sys v0.0.20 from example build failed 

### ISSUE THREAD

**Issue by DaniloZZZ** [exonum/exonum#1256]
Platform: Arch
rustc 1.32.0 (9fda7c223 2019-01-16)
cargo 1.32.0 (8610973aa 2019-01-02)
exonum master branch

I'm trying to build cryptocurrency-advanced example

```
cd examples/cryptocurrency-advanced/backend

cargo build
```
First, when compiling exonum_libsodium-sys v0.0.20, it tried to use lsb_release python module and failed since I don't have it. I have a second OS, Ubuntu 18.04, so I added folder with lsb_release module from mounted Ubuntu fs to PYTHONPATH.

Then compilation error was that python can't find /usr/share/distro-info/debian.csv . Again, I copied the file from Ubuntu fs to the /usr/share/distro-info/. After that, Python managed to import the lsb_release module. 

The error from compilation is now
```
   Compiling exonum_librocksdb-sys v0.5.4
   Compiling exonum_libsodium-sys v0.0.20
error: failed to run custom build command for `exonum_libsodium-sys v0.0.20`
process didn't exit successfully: `/root/bitfury/exonum/target/debug/build/exonum_libsodium-sys-2593a7f37d6f2ade/build-script-build` (exit code: 101)
--- stdout
OPT_LEVEL = Some("0")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = None
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")

--- stderr
thread 'main' panicked at 'Major version is not a number: ParseIntError { kind: InvalidDigit }', src/libcore/result.rs:1009:5

```

This probably comes from here: https://github.com/exonum/exonum_sodiumoxide/blob/cfb3df0ef926acd43b0920584bf186761c826b1d/libsodium-sys/build.rs#L192 
Where it seems to run `lsb_release -irs` command. 
on my system I have:
```
# lsb_release -irs
Arch rolling
```

**Comment by aleksuss** [comment]
@DaniloZZZ hello. Have you tried to install `libsodium` manually via apt for example?

**Comment by DaniloZZZ** [comment]
@aleksuss this worked, thanks!
