### ISSUE TITLE
How to build my network

### ISSUE THREAD

**Issue by hajsf** [exonum/exonum#1295]
Hi..
I need to start with this platform, I started reading the documentation which shows lots of great efforts but honestly speaking I could not know how to build the network, my be it is my mistake.
If I have 2 PCs, each one has its own IP address, what shall I do in each one, and how to connect them together as peers!

Can you please explain with little details, or guide me if there are such blogs!

**Comment by aleksuss** [comment]
@hajsf hello. You can see an example which demonstrates how to start a network with 4 nodes at this link: https://exonum.com/doc/version/latest/get-started/timestamping-tutorial/#start-the-blockchain-network Pay attention to the `--peer-address` parameter. In your case a value of this parameter should be an IP address of your PCs.

**Comment by hajsf** [comment]
Thanks @aleksuss 
Do I need to install all the dependencies as shown in the [get-started](https://exonum.com/doc/version/latest/get-started/install/) for each computer.
i.e. Do I need to setup each PC as if it is a stand alone development machine?
and DO I need to do the --peering in which machine with all other nodes?

**Comment by ivan-ochc** [comment]
> i.e. Do I need to setup each PC as if it is a stand alone development machine?
Yes.
> and DO I need to do the --peering in which machine with all other nodes?
Yes.

**Comment by hajsf** [comment]
Thanks @ivan-ochc 
So, if I understood correctly, if a --peer is missing in one nodes, then this node will not able to push or pull data from this --peer?
Nodes are pushing data to ALL --peers at the time of writing, but at the time of pulling data, how are they reading from one --peer only, or read from all and compare results before displaying out to the user, or how?

**Comment by aleksuss** [comment]
@hajsf if we're talking about consensus data than such kind of data is the same on ALL nodes. By the way, you can read in details about how our consensus works here: https://exonum.com/doc/version/latest/architecture/consensus/

**Comment by hajsf** [comment]
Thanks @aleksuss 
How can I access the [dashboard](https://exonum.com/dashboard), I filled the formed, but got no reply!

**Comment by Buzovska** [comment]
@hajsf Hasan, our sales team will contact you in the nearest time. Please keep in mind that the dashboard is available only for Exonum corporate partners. You can learn more about partnership terms here: https://exonum.com/partners

**Comment by hajsf** [comment]
Thanks @Buzovska 

Dears,
I looks there is something missing, may be from my side.
i tried following the steps in [start-the-blockchain-network](https://exonum.com/doc/version/latest/get-started/timestamping-tutorial/#start-the-blockchain-network), but stuck after the second step!!

```bash
Hasans-Air:backend h_ajsf$ cargo install --path .
  Installing exonum-timestamping v0.0.0 (/Users/h_ajsf/exonum/examples/timestamping/backend)
error: binary `exonum-timestamping` already exists in destination as part of `exonum-timestamping v0.0.0 (/Users/h_ajsf/exonum/examples/timestamping/backend)`
Add --force to overwrite
Hasans-Air:backend h_ajsf$ mkdir example
mkdir: example: File exists
Hasans-Air:backend h_ajsf$ ls
Cargo.toml	build.rs	example		src		tests
Hasans-Air:backend h_ajsf$ exonum-demo-timestamping generate-template example/common.toml --validators-count 4
-bash: exonum-demo-timestamping: command not found
Hasans-Air:backend h_ajsf$ 
```

**Comment by ivan-ochc** [comment]
For Exonum 0.11 use the following example:
https://github.com/exonum/exonum/tree/master/examples/timestamping#install-and-run-1

**Comment by hajsf** [comment]
Thanks @ivan-ochc it is fine now, but I did not get how you made it in the frontend using vue, what if I do not want to use vue, or not even using node, let's say I want to make the front end using [rocket](https://rocket.rs/)

**Comment by ivan-ochc** [comment]
@hajsf, it's up to you. You can use whatever you want.

**Comment by hajsf** [comment]
Thanks @ivan-ochc 
In rocket, for example, I can use 
```rust
request.set_uri("http://127.0.0.1:8200/");
```
Just wanted to cross check if I'm doing something wrong.

Another point pls, I could not find the function/implementation that save the `Timestamp` in the database, and where is the database itself is saved.

I saw this:
```rust
impl Timestamp {
    pub fn new(&content_hash: &Hash, metadata: &str) -> Self {
        Self {
            content_hash,
            metadata: metadata.to_owned(),
        }
    }
}
```

Moreover, how to read the data, I saw this:
```rust
Ok(schema.timestamps().get(&query.hash)
```
But could not find the `fn get()` itself

**Comment by aleksuss** [comment]
@hajsf 
1. What is a request do you want to make ?
2. A `timestamp` is saved into the database when a block commitment occurs.
3. `.timestamps()` method returns a `ProofMapIndex`. An implementation of the `ProofMapIndex` you can find [here](mpi)

[mpi]: https://github.com/exonum/exonum/blob/master/exonum/src/storage/proof_map_index/mod.rs

**Comment by hajsf** [comment]
Thanks  @aleksuss, the `mod.rs` is the only file I did not check, I thought it is just modules connections, I'll look into it, and come back with any clarification.

**Comment by ivan-ochc** [comment]
@hajsf, do you have any updates on your issue?
