### ISSUE TITLE
Error: Table proof is corrupted

### ISSUE THREAD

**Issue by ufosky** [exonum/exonum#1305]
platform: macOS
rust: 1.36.0-nightly
exonum: 0.11-master

When I follow steps from https://github.com/exonum/exonum/blob/master/examples/cryptocurrency-advanced/README.md , the backends and frontend are running OK with some minor changes(no code change, just command line argument changes), but I open the demo url and doing any action will always get error message notice "Error: Table proof is corrupted" . I want to know what's the problem and how to solve it.
![image](https://user-images.githubusercontent.com/801838/57135010-8f8a1480-6dda-11e9-81d2-8be822b87ea2.png)

**Comment by ivan-ochc** [comment]
@ufosky, it works fine within release [v0.11.0](https://github.com/exonum/exonum/tree/v0.11.0), you can use release instead of master.

**Comment by brailateo** [comment]
I confirm, it works with v0.11.0 TAG ...

**Comment by ivan-ochc** [comment]
Fixed - https://github.com/exonum/exonum/pull/1416
