### ISSUE TITLE
 docker run  -> (core dumped)

### ISSUE THREAD

**Issue by brailateo** [exonum/exonum#1313]
Ubuntu Linux 64 bit 18.04 LTS updated & upgraded , 4 CPU , 6 Gb RAM

Just:

$ docker run -p 8000-8008:8000-8008 exonumhub/exonum-cryptocurrency-advanced:demo

then 

Digest: sha256:ceb21b103381f319666f3f3e4031bc60acb465caba7e05d577b69fe717160f80
Status: Downloaded newer image for exonumhub/exonum-cryptocurrency-advanced:demo
./launch.sh: line 11:     9 Illegal instruction     (core dumped) $path_to_app generate-config common.toml pub_$((i + 1)).toml sec_$((i + 1)).toml --peer-address 127.0.0.1:${peer_port} -c consensus_$((i + 1)).toml -s service_$((i + 1)).toml -n
./launch.sh: line 11:    10 Illegal instruction     (core dumped) $path_to_app generate-config common.toml pub_$((i + 1)).toml sec_$((i + 1)).toml --peer-address 127.0.0.1:${peer_port} -c consensus_$((i + 1)).toml -s service_$((i + 1)).toml -n
./launch.sh: line 11:    11 Illegal instruction     (core dumped) $path_to_app generate-config common.toml pub_$((i + 1)).toml sec_$((i + 1)).toml --peer-address 127.0.0.1:${peer_port} -c consensus_$((i + 1)).toml -s service_$((i + 1)).toml -n
./launch.sh: line 11:    12 Illegal instruction     (core dumped) $path_to_app generate-config common.toml pub_$((i + 1)).toml sec_$((i + 1)).toml --peer-address 127.0.0.1:${peer_port} -c consensus_$((i + 1)).toml -s service_$((i + 1)).toml -n
. . .
loading config from sec_1.toml
error: Failed to load key config.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
. . .
> cryptocurrency-demo@1.0.0 start /usr/src/exonum/examples/cryptocurrency-advanced/frontend
> node server.js "--port=8008" "--api-root=http://127.0.0.1:8000"

[HPM] Proxy created: /  ->  http://127.0.0.1:8000
[HPM] Error occurred while trying to proxy request /api/explorer/v1/transactions from 127.0.0.1:8008 to http://127.0.0.1:8000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by ivan-ochc** [comment]
@brailateo, hi. I double checked that docker image on MacOS Mojave, Ubuntu 16, 18 and didn't have any issue. Just in case: what type of CPU do you have?

**Comment by brailateo** [comment]
On Mon, May 13, 2019 at 12:21 PM ivan-ochc <notifications@github.com> wrote:

> @brailateo <https://github.com/brailateo>, hi. I double checked that
> docker image on MacOS Mojave, Ubuntu 16, 18 and didn't have any issue. Just
> in case: what type of CPU do you have?
>

Intel i7 - 3930k

**Comment by ivan-ochc** [comment]
@brailateo, could you please try to build exonum-cryptocurrency-advanced [manually](https://github.com/exonum/exonum/tree/master/examples/cryptocurrency-advanced#manually)? Use tag 0.11.0 for this purpose.

**Comment by brailateo** [comment]
@ivan-ochc , we succeeded building it manually, starting with 0.11.0 , **everything is ok**, we also tested the Javascript client, making some money transfers.
BTW, we ran it approx. 24 hours and in this time he continued generating empty blocks, 3/4 per second, making 1.5 GB files on disk. This is the expected behavior or it can be tuned to "sleep" when no transactions are coming?
 Thanks and I must say that we are impressed with the fine and flexible architecture of Exonum, looking forward for a stable release point where we want to throw at it at least 200.000.000 transactions that we are keeping (for the moment) in a PostgreSQL database.

**Comment by ivan-ochc** [comment]
@brailateo, seems that your CPU doesn't support some SSE instructions, which is cause of such error. You can build your own docker image with help of [Dockerfile](https://github.com/exonum/exonum/blob/master/examples/cryptocurrency-advanced/docker/Dockerfile).

**Comment by brailateo** [comment]
Thanks @ivan-ochc , I'll do it!
