### ISSUE TITLE
Windows 10 build librocksdb-sys missing libclang (requires LLVM)

### ISSUE THREAD

**Issue by sigma67** [exonum/exonum#1364]
Platform: Windows 10 64bit 1903
Build: exonum-timestamping
Version: latest master 6e2bf45

After installing rust and protoc, compilation went fine up until librocksdb-sys v5.18.3. The error reported was "unable to find libclang". After installing LLVM 8 from [here](http://releases.llvm.org/8.0.0/LLVM-8.0.0-win64.exe), librocksdb installed fine. Unless there is another way besides installing LLVM, the [docs ](https://exonum.com/doc/version/latest/get-started/install/) should mention the requirement.

**Comment by ivan-ochc** [comment]
https://github.com/exonum/exonum-doc/pull/334

**Comment by sigma67** [comment]
Just a heads-up, the same librocksdb issue applies to Linux as well. apt install clang should be added to requirements

**Comment by ivan-ochc** [comment]
@sigma67, already fixed https://github.com/exonum/exonum-doc/pull/330/
