### ISSUE TITLE
Cryptocurrency Advanced Example:  generate-config

### ISSUE THREAD

**Issue by davebryson** [exonum/exonum#1401]
Using exonum master branch.

The README for manual setup seems to be out of date for some of the commands.  

For example, running the following results in an error:

```exonum-cryptocurrency-advanced generate-config example/common.toml example/pub_1.toml example/sec_1.toml --peer-address 127.0.0.1:6331 -c example/consensus_1.toml -s example/service_1.toml -n```

This fails as it seems the args to `generate-config` have changed:
```
error: Found argument 'example/sec_1.toml' which wasn't expected, or isn't valid in this context

USAGE:
    exonum-cryptocurrency-advanced generate-config [FLAGS] [OPTIONS] <COMMON_CONFIG> <OUTPUT_DIR> --peer-address <PEER_ADDRESS>
```
Overall, not a big deal, just FYI

**Comment by ivan-ochc** [comment]
@davebryson , https://github.com/exonum/exonum/pull/1402
