### ISSUE TITLE
exonum_leveldb::error::Error::new_from_i8 is unsafe

### ISSUE THREAD

**Issue by portstrom** [exonum/exonum#1409]
`exonum_leveldb::error::Error::new_from_i8` is not marked as unsafe, and unsafely dereferences the pointer given as an argument. This code causes a segmentation fault: `exonum_leveldb::error::Error::new_from_i8(1 as _);`

**Comment by vitvakatu** [comment]
Hello, @portstrom, thank you for creating an issue. Unfortunately `exonum_leveldb` is no longer supported by the Exonum team and we will not do any releases in the future. I suggest you to fork the crate by yourself (or use more modern ones, like [RocksDB](https://github.com/rust-rocksdb/rust-rocksdb)

**Comment by portstrom** [comment]
Even if you don't intend to maintain the crate anymore, you should leave the issue open so people know what issues there are in this crate.
