### ISSUE TITLE
Atomic consensus operation handles in api 

### ISSUE THREAD

**Issue by gisochre** [exonum/exonum#151]
- [ ] propose-get () - return propose
 - [ ] propose-submit () - broadcast propose
 - [ ] (prevote|precommit)-(get|submit) - handles to atomic operations of byzantine behavior

What are potential uses? 
For modeling byzantine behavior for tests from single center on a live testnet. Bulky and slow, but still.

**Comment by DarkEld3r** [comment]
Outdated.
