### ISSUE TITLE
merkledb/rocksdb fails to build with Rust 1.39.0

### ISSUE THREAD

**Issue by davebryson** [exonum/exonum#1535]
exonum-merkledb: `0.12.0`
Rust: `1.39.0`

The dependency version of rocksdb used by merkledb fails to build on Rust 1.39.0.  This appears to be a known issue and is close to resolution:  [RocksDB Release 0.13.0](https://github.com/rust-rocksdb/rust-rocksdb/issues/348)

**Comment by aleksuss** [comment]
Thanks for notice. I've released a new version of `librocksdb-sys` with fix for this issue already. Try to run `cargo update` and then rebuild once again.

**Comment by davebryson** [comment]
@aleksuss 👍 That worked.  Thanks!
