### ISSUE TITLE
Streaming hashing and signing with libsodium

### ISSUE THREAD

**Issue by defuz** [exonum/exonum#165]
1. Libsodium support streaming hashing and signing
2. But `sodiumoxide` (rust binding for libsodium) don't
3. We need it.

What to do:

1. Copy&paste sodiumoxide into 3rdparty (like leveldb)
2. Look at this PR: https://github.com/dnaq/sodiumoxide/pull/158
3. Implement streaming hashing and signing in our "fork"
4. Update `exonum::crypto`
5. Teach sodiumoxide to build without environment vars to simplify exonum build
6. Explore [maidsafe fork of sodiumoxide](https://github.com/maidsafe/rust_sodium) and borrow all the improvements from it.

**Comment by DarkEld3r** [comment]
Closed by #254.
