### ISSUE TITLE
RocksDB support

### ISSUE THREAD

**Issue by defuz** [exonum/exonum#178]
First steps:

1. Enable the use of RocksDB like LevelDB (on the top of `storage-refactoring-4` branch)
2. Do benchmarks for block execution and merging

Second steps:

1. Investigate rocksdb features: column family, transactions, bloom filters, statistics, backups...
...
2. Full transition to rockdb, get rid of leveldb

**Comment by dmitry-timofeev** [comment]
A couple of questions/concerns from the Java binding implementation perspective:

  - [ ] Can it be a replacement for MemoryDB:
    - [ ] Can you create multiple _in-mem_ databases and use concurrently in tests? Or does it require temporary files?
  - [ ] Will prefixes of indices be changed (= a new abstraction, e.g., an index name, with new restrictions)?
  - [ ] Will iterators over indices be independent (i.e., allow modifications of _other_ indices during iteration over one)?

@aleksuss, could you please keep them in mind during research/implementation, for our team doesn't expect answers immediately, rather we'd like to get them during implementation of this feature.

**Comment by DarkEld3r** [comment]
@dmitry-timofeev 
I definitely know only about prefixes: RocksDB has "column families" which are represented by strings (utf8 strings, at least in the Rust wrapper), so interface will be changed slightly (currently we allow arbitrary bytes as prefix).

**Comment by dmitry-timofeev** [comment]
Stanislav, thank you for the info. Will "column families" remain an abstraction of RocksDB (= hidden from our users behind an interface)? Will we have a new abstraction instead of index prefixes?

**Comment by DarkEld3r** [comment]
As far as I know, "column families" themselves will be hidden from the end users, but our interface still needs to be updated: "prefix" should be represented as string `&str` instead of bytes (`Vec<u8>`).

Probably @aleksuss can add more.

**Comment by dmitry-timofeev** [comment]
Then why would it be a "prefix" (= it's an _implementation_ detail of indices stored in `LevelDB`)?

**Comment by DarkEld3r** [comment]
@aleksuss  Should this be closed?

**Comment by aleksuss** [comment]
I suppose yes

**Comment by dmitry-timofeev** [comment]
Wait guys, could you please answer this first:

>  Will iterators over indices be independent (i.e., allow modifications of other indices during iteration over one)?

**Comment by aleksuss** [comment]
@dmitry-timofeev No, you won't be able to modify an entry via iterator.

**Comment by dmitry-timofeev** [comment]
@aleksuss There must be a misunderstanding, because the question was about a different thing. With LevelDb, if you iterate over an index and modify any _other_ index, that might invalidate the iterator (= you can't modify *anything* when iterating over any index). Is the same true for RocksDB?

**Comment by aleksuss** [comment]
@dmitry-timofeev Sorry. I misunderstood your question. A modification of index not affect an iterator of other index.
