### ISSUE TITLE
Compiling Exonum for the 1st time

### ISSUE THREAD

**Issue by erdeivit** [exonum/exonum#1808]
After following the install guide in an Ubuntu VirtualBox I reach the "Compiling Exonum" part.

After running "cargo test -p exonum" I get the following error:

  Compiling os_info v2.0.1
error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
 --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/os_info-2.0.1/src/bitness.rs:6:1
  |
6 | #[non_exhaustive]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/44109

error[E0658]: the `#[non_exhaustive]` attribute is an experimental feature
 --> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/os_info-2.0.1/src/os_type.rs:7:1
  |
7 | #[non_exhaustive]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/44109

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `os_info`.

To learn more, run the command again with --verbose.

¿Any help?

**Comment by integrer** [comment]
Hello! I think you must use cargo from nighty channel. (https://stackoverflow.com/a/48594752)

**Comment by slowli** [comment]
Hi, @erdeivit! What's the Rust compiler version you're using? (It can be found by running `rustc --version` or `rustup show`.) The `master` branch targets the latest stable (1.41) and is not guaranteed to run on earlier Rust versions. The badges in various readmes stating that Exonum supports Rust 1.36+ are thus outdated; we plan to update them soon.

If the Rust version *is* the issue, it can be solved by updating the Rust toolchain with the `rustup update stable` command.

**Comment by erdeivit** [comment]
Oh it seems that doing that works. After running hundreds of tests, most of them were okey and others ignored or with warnings but none failed.

**Comment by erdeivit** [comment]
@slowli 
I have just installed everything. I have rustc 1.41.1 (2020-02-24).

**Comment by aleksuss** [comment]
@erdeivit Could you close the issue please if everything is ok ?
