### ISSUE TITLE
Crytocurrency Example Service

### ISSUE THREAD

**Issue by erdeivit** [exonum/exonum#1810]
After donwloading exonum and following the Installation Guide, I tried the first of the tutorials. As the Cryptocurrency: Example Sercive tutorial was already downloaded in the repository itself, I simply tried to run it:

# build and run a zero-configuration demo
charge run --example demo

I have the following error:

Compiling os_info v2.0.1
error [E0658]: the `# [non_exhaustive]` attribute is an experimental feature
 -> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/os_info-2.0.1/src/bitness.rs:6:1
  |
6 | # [non_exhaustive]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/44109

error [E0658]: the `# [non_exhaustive]` attribute is an experimental feature
 -> /home/david/.cargo/registry/src/github.com-1ecc6299db9ec823/os_info-2.0.1/src/os_type.rs:7:1
  |
7 | # [non_exhaustive]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/44109

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `os_info`.

To learn more, run the command again with --verbose.

As for the versions, I should have all the latest, since I just installed everything in a virtual machine with Ubuntu.

Any help?

**Comment by aleksuss** [comment]
@erdeivit It seems that you use a not fresh compiler. Try to update it. Just run:
```bash
rustup update
```

**Comment by erdeivit** [comment]
The problem is that you need to run it in night mode, which is not said anywhere. Doing that, works fine.
