### ISSUE TITLE
exonum_merkledb crate uses rocksdb 0.13.0, is there a plan to upgrade to rocksdb 0.15.0 

### ISSUE THREAD

**Issue by kishoreneelamegam** [exonum/exonum#1887]
Hello

I am using your create exonum_merkledb crate to build the cache logic on top of postgres. This has been working well.
I see that the official crate version pulls rocksdb 0.13.0.

But the git master branch code says you have `rocksdb = "0.15.0"`.

Is there a plan to push an update for exonum_merkledb crate?

**Comment by aleksuss** [comment]
Hello. Yes. In nearest future I plan to bump `rocksdb` version from 0.13 to 0.15.

**Comment by indykish** [comment]
Looking forward to it.

When is the next release planned for exonum-merkledb ?
