### ISSUE TITLE
Concerns About Actix For a Security Oriented Software Project

### ISSUE THREAD

**Issue by zicklag** [exonum/exonum#1913]
Hey there, I'm evaluating exonum for a project and I noticed its use of the Actix web framework for the API ( I'm not 100% sure to what extent it is used but a quick look seems that it is used for the REST endpoints ). While I'm fine with it for experimentation, I'm personally reluctant to use Actix in a security-critical context due to the maintainers stance on undefined behavior and community management:

https://github.com/MaulingMonkey/rust-reviews/blob/master/reviews/actix-web.md

While the Exonum project may have a high standard for security, the Actix project seems to have much less so and could potentially be a source of vulnerabilities. I personally have started using the Warp project instead of Actix and have been very satisfied with it. Is there perhaps a way to swap Actix out with Warp, even if not for this project, but for my own apps made with Exonum?

**Comment by stanislav-tkach** [comment]
Isn't this review a bit outdated? As far as I know, the original developer has stepped out from the project. Though I'm not sure if soundness issues are fixed.

**Comment by zicklag** [comment]
Ah, maybe it is, I hadn't been following development. If that is the case it may not be a problem. You probably know more than I do about it.

**Comment by stanislav-tkach** [comment]
To be clear: I'm no longer working on this project, though I'm using actix-web on another non-blockchain project.

**Comment by augustocdias** [comment]
I'm not a maintainer of actix but I use it for quite some time and the new maintainers are doing a nice job there. They're quite open for contribution and feedback and they're very active. I don't believe this is a valid concern anymore.

**Comment by zicklag** [comment]
OK, cool. :) I'm good closing this in that case. I definitely am no authority on its maintenance status. I ended up liking warp more anyway, but I'm glad Actix isn't so scary anymore. :smiley:
