### ISSUE TITLE
Hide raw data of the vector-based structs

### ISSUE THREAD

**Issue by DenisKolodin** [exonum/exonum#192]
The struct created with `encoding_struct!` macro provides direct access to the deep raw data. We even have to update it that way: `Field::write(&<value>, &mut self.raw, <from>, <to>);`. But it is fragile.

I'm sure we need:
1. Hide the raw data (we can provide immutable reference to it by method call)
2. Use builder instead of direct overwriting of the field

It's applicable to `message!` and `encoding_struct!` macros.

**Comment by DarkEld3r** [comment]
Outdated.
