### ISSUE TITLE
Can no longer compile Crypto Currency Advanced - weird error doesn't make sense to me

### ISSUE THREAD

**Issue by davidoabile** [exonum/exonum#2005]
Hi all,

I think I am losing it, I can't compile the project below using the instructions below:

Build the project:

```sh
git clone https://github.com/exonum/exonum
cd exonum/examples/cryptocurrency-advanced/backend
cargo install --path .
```

I tried form rustc 1.45 and even the latest rust 1.55 on Ubuntu 21.

The error is simple. It states that I should use `use secrecy::ExposeSecret;` even though it has been used and later on it states that `use secrecy::ExposeSecret;` is unused 

I even tried putting it first and that does not fix the problem.

` Compiling exonum-keys v1.0.0 (/home/sc_workspace/exonum/components/keys)
error[E0599]: no method named `expose_secret` found for reference `&secrecy::Secret<[u8; 32]>` in the current scope
   --> components/keys/src/lib.rs:172:36
    |
172 |             .seal(pass_phrase, key.expose_secret())
    |                                    ^^^^^^^^^^^^^ method not found in `&secrecy::Secret<[u8; 32]>`
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
57  | use secrecy::ExposeSecret;
    |

warning: unused import: `secrecy::ExposeSecret`
  --> components/keys/src/lib.rs:60:5
   |
60 | use secrecy::ExposeSecret;
   |     ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

`
![error-exomun](https://user-images.githubusercontent.com/1709835/133949653-a17bf441-4a96-4022-8694-c7cc581d5659.png)

If anyone can help, that will be appreciated.

Thanks.

**Comment by aleksuss** [comment]
Hello. Current master has already changes which fix the issue.

**Comment by davidoabile** [comment]
Appreciate your quick response and it has fixed the issue.

Thank you.
