### ISSUE TITLE
API endpoints HTTP error code

### ISSUE THREAD

**Issue by VukW** [exonum/exonum#233]
Now, if API raises an `ApiError`, user receives an `HTTP 409 Conflict` error. As for me, the `400 Bad Request` or `406 Not Acceptable` suits better.
Example: Exonum Core, `http://127.0.0.1:7780/api/explorer/v1/blocks`. If no block hash specified, then `HTTP 409 Conflict` is returned
@defuz @vldm @slowli

**Comment by ivan-ochc** [comment]
Issue is outdated
