### ISSUE TITLE
Proofread "reference documentation"

### ISSUE THREAD

**Issue by DarkEld3r** [exonum/exonum#245]
All "reference documentation" must be proofread both for grammatic errors (by a technical writer?) and for logical correctness (understandability) (by analytics?).

**Comment by djsatok** [comment]
Is this still in progress? @Maria-Nosyk?

**Comment by Maria-Nosyk** [comment]
@djsatok it is

**Comment by slowli** [comment]
@Maria-Nosyk Just a couple of places that caught my attention:
- [`storage` module doc](https://docs.rs/exonum/0.3.0/exonum/storage/index.html) should be updated according to 0.3 release (e.g., mentions of LevelDB should be removed). Also, general grammar fixes (e.g., fix "MemoryDB presents always.")
- [`blockchain` module doc](https://docs.rs/exonum/0.3.0/exonum/blockchain/index.html) mentions "minibank tutorial", which should be changed to "cryptocurrency tutorial". Also, some types in the module mention `exonum-core`, which probably should be changed to "Exonum core" or simply "Exonum"
- Macros documentation is clunky: [`metric`](https://docs.rs/exonum/0.3.0/exonum/macro.metric.html) is seemingly unfinished, [`encoding_struct`](https://docs.rs/exonum/0.3.0/exonum/macro.encoding_struct.html) and [`message`](https://docs.rs/exonum/0.3.0/exonum/macro.message.html) have some awkward grammar.

**Comment by DarkEld3r** [comment]
> metric is seemingly unfinished...

...and wrong. :sweat_smile: Macro implementation has been changed and documentation has not. Hopefully, it will be changed soon.

**Comment by DarkEld3r** [comment]
Mostly done.
