### ISSUE TITLE
Problem with compiling (libsodium)

### ISSUE THREAD

**Issue by EvgeniyKorzhanov** [exonum/exonum#266]
After Cargo run, in terminal: 

error: failed to run custom build command for `libsodium-sys v0.0.14`
process didn't exit successfully: `/Users/evgenykorzhanova/cryptocurrency/target/debug/build/libsodium-sys-b8e056784be62f0f/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libsodium\"`: No such file or directory (os error 2)"', src/libcore/result.rs:860
note: Run with `RUST_BACKTRACE=1` for a backtrace.

Who can help fix this problem?

**Comment by vldm** [comment]
You need to install `pkg-config` additionally to other libs:
```shell
 brew install libsodium leveldb
```
according to changes in https://github.com/exonum/exonum-doc/pull/111

Suddenly this pr didn't merged into production yet.

**Comment by EvgeniyKorzhanov** [comment]
Thanks! its work
