### ISSUE TITLE
Wrong JSON serialization

### ISSUE THREAD

**Issue by DenisKolodin** [exonum/exonum#269]
This code produces wrong JSON output:
```rust
[macro_use] extern crate exonum;
extern crate serde;
extern crate serde_json;
#[macro_use] extern crate serde_derive;

encoding_struct! {
    struct Wallet {
        const SIZE = 8;

        field balance:            u64         [00 => 08]
    }
}

#[derive(Serialize)]
struct RawWallet {
    balance: u64,
}

fn main() {
    let wallet1 = Wallet::new(0);
    let json1 = &serde_json::to_value(&wallet1).unwrap();
    let wallet2 = RawWallet { balance: 0 };
    let json2 = &serde_json::to_value(&wallet2).unwrap();
    println!("JSON: {} vs {}", json1, json2);
}
```

It prints:
```
JSON: {"balance":"0"} vs {"balance":0}
```

We get a `String` instead of an `Integer`.

**Comment by DarkEld3r** [comment]
JavaScript doesn't have 64 bit integers. :smile:

**Comment by DenisKolodin** [comment]
Right, but serde handles it better. We should use float number format to represent numbers in JSON.

**Comment by slowli** [comment]
@DenisKolodin Could you please clarify a little bit what you mean by float number format? I'm against using any floating-point arithmetic on the blockchain as humanely possible; it's often non-deterministic (which is unfortunate given how JS handles numbers 😩 ).

To give a concrete example: how would `RawWallet` be serialized if its balance was `1234567890987654321`? I tried and got `{"balance":1234567890987654321}`, which strikes me as something that JS's built-in `JSON.parse` won't parse correctly, even with a custom reviver. Do you suggest to use a custom JSON parser for JS?

**Comment by gisochre** [comment]
@DenisKolodin String-s for u64/i64 are used by design.

**Comment by DenisKolodin** [comment]
I'm of one mind with you, but it doesn't look like traditional JSON. What about to add extra metadata to demystify it: `{ "_type": "u64", "value": "12345678901234567890" }`?

**Comment by slowli** [comment]
I don't know about this; the serialization format in Exonum is not self-descriptive (just like JSON), but is rather based on an external schema. This schema contains datatype definitions, so the client should know if a particular field should be a string or a stringified `u64`. On the other hand, could you please provide references for traditional JSON - maybe, it'll make things clearer? `{ "_type": "u64", ... }` looks like a tagged union encoding (say, in serde, or Jackson), but the encoded type is not a union, so I don't quite get why the `_type` marker is needed.

**Comment by vldm** [comment]
@DenisKolodin  Btw, as far as I know, in js type system is not strict enough, and `"123"` is a valid INTEGER value too

**Comment by slowli** [comment]
@vldm Do you mean the type system allows interpreting strings as numbers in some contexts? Yeah, this happens (say, `+'123' === 123`, and `'foo'['2'] === 'o'`). However, [JS numbers](http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-types-number-type) are separate from strings, and it's possible to distinguish between them, e.g., via `typeof` operator or strict equality `===`.

**Comment by DenisKolodin** [comment]
@vldm I've tried it in console. JS treats it as string:
```
JSON.parse('{"balance": "123"}')["balance"] + 2 == "1232"
// but
JSON.parse('{"balance": "123"}')["balance"] * 2 == 246
```
Watch, please: https://www.destroyallsoftware.com/talks/wat )

**Comment by slowli** [comment]
> JSON.parse('{"balance": "123"}')["balance"]

I don't think we should use *any* JSON passed from the server, without sanitation / schema verification; it's plain unsecure. (This is incidentally one of the reasons I don't quite like `exonum-client` in its current form).

**Comment by vldm** [comment]
@DenisKolodin So, what we shall do about it? 
`JSON` - didn't specify the number format, but аdvises to use `binary64`, which is "widely used".
`u64` - is an unsigned integer 64bit long, which upper values cannot be represented as a valid `binary64`.

If `exonum` will ignore JSON specification "advise", then Javascript will not be able to map this JSON as an JS object (Light client will lose accuracy).
So `exonum` has a specific JS compatibility layer, to encode 64-bit long unsigned digits into a valid form. JS client handle this "strings" as `BigInt`

For naive use, js can easily convert this string into int.

**Comment by DenisKolodin** [comment]
Ok, I think we should use RFC process to propouse this kind of changes.
