### ISSUE TITLE
Can't compile master on stable Rust

### ISSUE THREAD

**Issue by hiseni** [exonum/exonum#290]
Currently, due to changes in upstream Rust, ```#[feature]``` can't be used on stable channel anymore and throws a compile time error.

![stable-flamer](https://user-images.githubusercontent.com/8407846/29062805-d731659c-7c2b-11e7-928a-9662ec6ed0af.png)

rustc 1.19.0 (0ade33941 2017-07-17)
cargo 0.20.0 (a60d185c8 2017-07-13)

**Comment by DarkEld3r** [comment]
Could you please show your build command (full output ideally)? 

Unfortunately, if you need to profile Exonum, then you need nightly rust, but this should not be a problem because `exonum_flamer` is enabled via feature, so it should not build by default.

**Comment by vldm** [comment]
Currently `flame_profile` feature, works only with some limited version of nightly rust.

**Comment by hiseni** [comment]
@DarkEld3r here is full output:

![flamer-full](https://user-images.githubusercontent.com/8407846/29084014-6653b12a-7c73-11e7-9c7a-12a2e3df0174.png)

I use ```--all``` flag to check all packages.

As I got it: this attribute is not for stable, thus only **a part of core workspace will build on stable**.

For now I'm closing this issue, thanks for clearance.
