### ISSUE TITLE
Improve clap fabric usability.

### ISSUE THREAD

**Issue by alekseysidorov** [exonum/exonum#311]
I have several suggestions for improving usability of clap fabric.

- [ ] Specify in the core prefixes for specific keys, for example, keys for anchoring must have `anchoring` prefix. 
- [ ] Implement command line keys to set public and private api addresses.
- [ ] Allow creating auditor node, from cli. https://github.com/exonum/exonum/issues/316
- [ ] Add optimal `propose_timeout ` value to template generated by `generate-template` command

**Comment by vldm** [comment]
https://github.com/exonum/exonum/issues/316 should be part of this

**Comment by ivan-ochc** [comment]
Issue is outdated
