### ISSUE TITLE
Missing encoding implementation for `Map<K, V>`

### ISSUE THREAD

**Issue by vldm** [exonum/exonum#319]
Exonum should contain implementation of `SegmentField` for  Key-Value storage.

This `Map` should be probably ordered like `BTreeMap` to achieve `zero-cost` requirement.

**Comment by DarkEld3r** [comment]
Wouldn't it be convenient to support all standard types in addition to our special optimized versions?

**Comment by vldm** [comment]
@DarkEld3r No, I am pretty sure in `encoding` shema types should be separate from std lib, because we need to feet other properties.
But there should be compatibility layer, that will convert `std::collections` into `encoding::collections` and backward.

**Comment by aleksuss** [comment]
Closed as outdated
