### ISSUE TITLE
Add macro for collecting metrics

### ISSUE THREAD

**Issue by DarkEld3r** [exonum/exonum#320]
Macro similar to the logging macros (`error!`, `trace!`, etc.) should be added for collecting different metrics.

**Comment by vldm** [comment]
Can you explain, what do you mean when tell "collecting different metrics".
What kind of metrics we can collect?
Should it be dynamic api or static? (why macro)

**Comment by DarkEld3r** [comment]
This task includes gathering different (for example, network) statistics, so it supersedes #153 issue.

**Comment by DarkEld3r** [comment]
Additionally we need more endpoints for dashboard (#321).

**Comment by DarkEld3r** [comment]
@vldm This task is currently in a very raw state, I will update it when details become clearer.
