### ISSUE TITLE
Building project with cargo workspace, cause building exonum with memorydb

### ISSUE THREAD

**Issue by vldm** [exonum/exonum#327]
Consider the following structure:
```
├── Cargo.lock
├── Cargo.toml
├── README.md
└── backend
    ├── Cargo.lock
    ├── Cargo.toml
    ├── src
    │   ├── main.rs
    │   └── service.rs
```

Building this project with `cargo build -p` or with `cargo install` cause cargo to ignore `default` exonum feature.
This cause exonum to fallback into memorydb.

**Comment by DarkEld3r** [comment]
Fixed.
