### ISSUE TITLE
Execute other transactions from `Transaction::execute()`

### ISSUE THREAD

**Issue by Ralvke** [exonum/exonum#328]
Its possible?

E. g.
```rust
message! {
    struct WalletTransfer {
        const TYPE = consts::core::SERVICE_ID;
        const ID = consts::tx::TRANSFER_WALLET;
        const SIZE = 80;

        field from:   &PublicKey  [00 => 32]
        field to:     &PublicKey  [32 => 64]
        field amount: u64         [64 => 72]
        field seed:   u64         [72 => 80]
    }
}
// ------------------------------------------------
impl Transaction for OtherTx {
    fn execute(&self, view: &mut Fork) {
        let mut schema = Schema { view };
        // ------------------------------------------
        let transfer = WalletTransfer::new(..., &gen_keypair().1);
        transfer.execute(view); // cannot borrow `view`
    }
}
```

**Comment by Maria-Nosyk** [comment]
Transactions are atomic units that are executed only once and entirely with further conservation in the blockchain. Thus, a transaction cannot exist within another transaction as a minimal logical operation.

Transactions in Exonum are internal entities managed by the core and cannot be detached from it. In other words, in order core could execute a transaction the latter must be created and placed into the transactions pool (distributed among the network). Only afterwards it can be included into the block and executed by the core. Thus, it is not possible to apply the transaction as a simple function neglecting mechanism of the core.

Judging from your example we suggest two possible solutions:
1) In case you have two transactions, A and B, and transaction B inherits logic of transaction A, you may try to incorporate the repeating code into a separate function and call it whenever required.

2) In case transaction A is executed whenever the system reaches a certain prescribed state and some independent transaction causes said system state we suggest that you use the following method:
https://github.com/exonum/exonum/blob/master/exonum/src/blockchain/service.rs#L99
This method is called on block commit and it can create new transactions whenever the system reaches a prescribed state (method `add_transaction` of `ServiceContext` structure).

For further assistance please provide more information on the case.

**Comment by Ralvke** [comment]
Thanks
