### ISSUE TITLE
Execute transaction on init

### ISSUE THREAD

**Issue by Ralvke** [exonum/exonum#334]
How do transaction on init (before mount API)?
I'm can make `Fork` from Blockchain, create `Schema` from then, edit `Schema` state, but cant make patch for Blockchain (`into_patch()` borrowing `Fork`)

**Comment by Ralvke** [comment]
Impl `Clone` for `Fork`?

**Comment by gisochre** [comment]
@Ralvke can you add an exemplary code snippet to clarify what you're trying to achieve.

**Comment by Ralvke** [comment]
```rust
```

**Comment by Ralvke** [comment]
Oh my god, all works fine with just tx (not creating `Schema{}` and modify it)
Sorry, my mistake

Correct code 
```rust    
let blockchain = Blockchain::new(Box::new(db), services);

// execute some tx before run node
let mut fork = blockchain.fork();
let some_tx = transactions::CreateWallet::new(...);
some_tx.execute(&mut fork);
let patch = fork.into_patch();
blockchain.merge(patch);

let mut node = node::new(cfg.node, blockchain).unwrap();
node.run().unwrap();
```
