### ISSUE TITLE
Transactions order in Snapshot

### ISSUE THREAD

**Issue by Ralvke** [exonum/exonum#344]
Hi 
Method [`Schema::transactions()`](https://docs.rs/exonum/0.2.0/exonum/blockchain/struct.Schema.html#method.transactions) should returns txs in correct order?

I am need watch all txs and I use [`handle_commit()`](https://docs.rs/exonum/0.2.0/exonum/blockchain/trait.Service.html#method.handle_commit) for this
```rust
    fn handle_commit(&self, context: &mut ServiceContext) {
        let schema = Schema::new(context.snapshot());
        let txs = schema.transactions();

        txs.iter().for_each(|(hash, _)| println!("{:?}", hash));
        println!("-----------------------");
    }
```
After I ran it and made five txs.
Console (with added correct order):
```
Hash(85131EB7) // 1
-----------------------
Hash(85131EB7) // 1
Hash(FC383EA) // 2
-----------------------
Hash(2AAE1E38) // 3
Hash(85131EB7) // 1
Hash(FC383EA) // 2
-----------------------
Hash(2AAE1E38) // 3
Hash(85131EB7) // 1
Hash(C39EA755) // 4
Hash(FC383EA) // 2
-----------------------
Hash(2AAE1E38) // 3
Hash(4D40822D) // 5
Hash(85131EB7) // 1
Hash(C39EA755) // 4
Hash(FC383EA) // 2
```
As seen, txs printed not in the order

Actually I need watch all _new_ txs and using [`iter_from()`](https://docs.rs/exonum/0.2.0/exonum/storage/map_index/struct.MapIndex.html#method.iter_from) (with hash stored in Service state) not works

**Comment by quicky84** [comment]
It actually seems they are in lexicographic order w.r.t. the hash value; say, the last bunch --- 2, 4, 8, C, F

**Comment by DarkEld3r** [comment]
Sorry for the delayed response. @quicky84 is right: transactions hash is used as the key, so they are sorted lexicographically. Perhaps, you should use `Schema::block_txs` to get transactions from the given block.

Feel free to re-open the issue if you still have questions.
