### ISSUE TITLE
Explorer API range endpoint

### ISSUE THREAD

**Issue by quicky84** [exonum/exonum#346]
Current design of the [blocks-in-range API](https://exonum.com/doc/advanced/node-management/#public-endpoints) does not allow for easy retrieval of the blocks in the chain.
For example, you would like to retrieve only non-empty blocks from the tail of the chain, thus `GET {explorer_base_path}/blocks?count=k&skip_empty_blocks=true`. Imagine that the last k+1 blocks are empty, then the result will be `[]`. Client-side it's not possible to conclude whether you exhausted all blocks (there no transactions in the chain) or just hit a range of (at least k+1) empty blocks. There is no way to continue exploring the chain because you don't know the heights of the involved blocks or, at least, the height of the latest block. See also exonum/exonum-doc#132

For now, the workaround is to retrieve all blocks starting from the tail until you hit the first block and then filter on `tx_count`.

**Comment by tipoc123** [comment]
vote up!

**Comment by DarkEld3r** [comment]
Closed with #509.
