### ISSUE TITLE
Compiling Exonum error:

### ISSUE THREAD

**Issue by EvgeniyKorzhanov** [exonum/exonum#414]
What can be and what can i do to fix this error:

Compiling podio v0.1.6
error: use of unstable library feature 'float_bits_conv': recently added (see issue #40470)
   --> /Users/MyUserName/.cargo/registry/src/github.com-1ecc6299db9ec823/podio-0.1.6/src/lib.rs:243:29
    |
243 |         let tval: u32 = val.to_bits();
    |                             ^^^^^^^

**Comment by DarkEld3r** [comment]
What rust version are you using? 
Probably, you should use a newer one (for example 1.23).

**Comment by EvgeniyKorzhanov** [comment]
i install Rust v. 1.23.0 stable

**Comment by DarkEld3r** [comment]
> i install Rust v. 1.23.0 stable

Did it help?

**Comment by EvgeniyKorzhanov** [comment]
no, i try delet all (rast, libsodium, db, framework exonum) and install again how writing in the guide exonum, but result - error

Отправлено с iPhone

**Comment by vitvakatu** [comment]
Well, that's weird. `podio` indeed uses `f32::to_bits` function, but this function was implemented in Rust 1.20, more than four months ago.

@EvgeniyKorzhanov do you use `rustup` for Rust installation? If so, can you provide the output of `rustup show` command?

**Comment by EvgeniyKorzhanov** [comment]
like this: curl https://sh.rustup.rs -sSf | sh

Отправлено с iPhone

**Comment by vitvakatu** [comment]
@EvgeniyKorzhanov unfortunately, I can't find your contacts. Could you contact me via `ilya.bogdanov@xdev.re`? I believe we can find out what's going on and help you faster in that case.

**Comment by EvgeniyKorzhanov** [comment]
Thanks for help, korzhanov.info@gmail.com

Отправлено с iPhone

**Comment by vitvakatu** [comment]
The problem has been solved privately, closing now.
