### ISSUE TITLE
Different Versions of "Contributing" guidelines

### ISSUE THREAD

**Issue by lazaridiscom** [exonum/exonum#432]
#### Expected Behavior

"Single Point of Truth", ideally right within the project repository

#### Actual Behavior

There are two (similar but different) "Contributing" documents. One in the project repo(here) and one in the docs:

* https://github.com/exonum/exonum/blob/master/CONTRIBUTING.md
* https://exonum.com/doc/contributing

#### Possible Solution

* The code-repo Contribution.md becomes the only relevant document.
* Relevant parts of "https://exonum.com/doc/contributing/" are moved into the code-repo Contribution.md
* "Contributing to Exonum" is then minimized to something like:

> You are welcome to contribute to exonum in an usual Open Source manner. Please visit the project and ensure that you read through the [Contributing Guidelines](https://github.com/exonum/exonum/blob/master/CONTRIBUTING.md).

**Comment by lazaridiscom** [comment]
Yes, its difficult to decide, i struggle myself.

The way out of this struggle is to realize that `Exonum` is both, a Project and(!) a Product.

The "documentation" (https://exonum.com/doc/) is something like a manual for the exonum product(!), thus it should not deal with exonum project processes.

The "contributing" document is something like a manual for the exonum project(!), thus it belongs to the core project (exonum/exonum). Other exonum projects simply point back to the core-project.

Another rationale: "Contributing.md" is a process-document, which should be under control of the core-team (exonum/exonum).

**Comment by DarkEld3r** [comment]
Closed by #482.
