### ISSUE TITLE
Inconsistent Project Naming (dash vs. underscore)

### ISSUE THREAD

**Issue by lazaridiscom** [exonum/exonum#434]
#### Expected Behavior

All exonum projects share common naming rules

#### Actual Behavior

Two projects:

* exonum/exonum_sodiumoxide
* exonum/exonum_rocksdb

use an underscore instead of a dash. 

#### Expected Solution

The two projects should be renamed, the earliest possible.

Alternatively, the inconsistency should be explained (e.g. within a dedicated Project Manual, which addresses mainly the core-developers).

**Comment by DarkEld3r** [comment]
This is a bit controversial, but the idea behind such naming was the following: "internal" crates should use underscore instead of dash. There is no strong motivation, though.

Probably, we are going to use `rocksdb` crate (instead of `exonum_rocksdb`) anyway because it is actively maintained at the moment.

**Comment by lazaridiscom** [comment]
(crates = "module" in rust-langue)

> "internal" crates should

What is the meaning of "internal" here? Both modules look like rust-bindings/wrappers to external libraries/tools.

> Probably, we are going to use rocksdb crate

https://crates.io/crates/rocksdb

It seems that this would be the way to go.

**Comment by DarkEld3r** [comment]
> What is the meaning of "internal" here?

"Public" crates (such as `exonum`, `exonum-configuration` or `exonum-testkit`) are intended to be used by the community: we are going to support them.
"Internal" crates (which are technically also public and published on crates.io) are only needed in case if the existing community crates do not fulfill our requirements and we cannot send a pull request for some reason (or need a quick solution).

> https://crates.io/crates/rocksdb

Yes, I mean exactly this crate.

> (crates = "module" in rust-langue)

Not exactly, by the way. 😄

**Comment by lazaridiscom** [comment]
I understand.

Possibly `custom` or `fork` would be the way to go.

Applied to the name: `custom-rust-rocksdb`. 

Or: `exonum-rust-rocksdb`

But then ok, naming entities is a small hell for itself.

Just be aware that the term `internal` is misleading

>> (crates = "module" in rust-langue)
>
>Not exactly, by the way. 😄

Sorry, my fault!
 
=> "A crate is synonymous with a ‘library’ or ‘package’ in other languages"

from: https://doc.rust-lang.org/book/first-edition/crates-and-modules.html

.

**Comment by DarkEld3r** [comment]
@lazaridiscom If you are still interested, we have some news on these topic.

Our [pull request](https://github.com/spacejam/rust-rocksdb/pull/166) in the rocksdb crate has had no feedback for almost a month. As for sodium, we are waiting for a decision on [this issue](https://github.com/dnaq/sodiumoxide/issues/192).

Thus, we are going to use our forks at least for some more time.

**Comment by lazaridiscom** [comment]
@DarkEld3r , I just pointed out an inconsistency in naming.

Now, to the PR merge problem: if you ask a maintainer to merge something that he cannot understand fully... he will most possibly not merge. So, if your architectural thinking is above average, you'll have usually problems to get your PR done.

Seeing the [monthly status or rust-rocksdb](https://github.com/spacejam/rust-rocksdb/pulse), you should possibly arrange to continue maintenance of the rocksdb package.

Can be `exonum-rocksdb`, so other users know its maintained by the exonum project. The you have to assess other users functionality wishes, and hopefully merge faster that the original project.

So, if those 2 packages are important to the exonum project, make forks, make them better that the originals, stay compatible, extend functionality, and let other developers adopt them.

I would go this way, if each and every PR becomes a time/energy sink.
