### ISSUE TITLE
Website: Some Major-Minor Issues

### ISSUE THREAD

**Issue by lazaridiscom** [exonum/exonum#435]
(Note: I'm a **veteran** to IT (software & electronics), and a **newcomer** to the blockchain domain)

This is a collection of issues. It addresses essentially the C-level (as in Cxx like CEO, CTO etc.).

* The product website (exonum.com) is **primarily** a marketing-instrument
* The website (exonum.com) should **prominently** mention strengths.
* Category: Exonum is a framework for the creation of **private** blockchains.
* Strength: Exonum has real-life government-level Success Stories
* Exonum is backed by a commercial entity (bitfury.com)

See, you may think "everyone in the blockchain business domain knows Bitfury". Newcomers do not, and if an evaluator has to fight through the masses of frameworks and tools, he may oversee that a quite impressive company is behind the exonum project.

### Support

For me (in the role of an evaluator who has to pick a blockchain-toolset), those are some of the relevant requirements:

* Exonum source-code is available 100% under a liberal open-source-license.
* The project is really open, it encourages contributions from different folks
* Commercial support is available (Question: does bitfury provide commercial support? )
* Missing: a clear pointer to the commercial entity which support the project.

### Menu

Current Menu: 

EXONUM - FRAMEWORK - USE CASES - PARTNERS - RESOURCES - CONTACT US

* "Framework" **could** be renamed to "Product"
* "USE CASES" could be renamed to "Quick Start" (Demos should be made available in sourc-code, enabling a very fast project-start.
* "PARTNERS" could be renamed to "SUCCESS STORIES", where exonum shows his real-life success
* RESOURCES could be renamed to "PROJECT", separating clearly the projec-related stuff. Should contain a TEAM submenu
* CONTACT US should contain some basic contact-info (instead of a direct email-link)

Suggested Menu:

EXONUM - PRODUCT - DEMOS - STORIES - PROJECT - CONTACT

alternatively: DEMO = "QUICK STARTS", STORIES =>"SUCCESS STORIES"

It is important that the landing-page shows immediately the most relevant "product classifications" (e.g.: private blockchain), the most impressive success story, and the easiest quick-start (get a system up and running in under an hour, including source-code etc.).

Ideally, the landing-page would mention the commercial backup (Bitfury). An indirect decent way to do so is to mention "Commercial Grade Support" available (which is an absolute plus for an open-source project).

### Mockup

All this above can trigger "a discussion till the death". It has sometimes less effort to create a "mockup" and show suggestions than to discuss them. This would be simplified by making the website sources available (see: exonum/exonum-doc#163)

**Comment by DarkEld3r** [comment]
@slowli Could you please take a look and comment if possible? :smile:

**Comment by DarkEld3r** [comment]
@lazaridiscom 
Thank you for your suggestions, but our vision for such things is slightly different.

Additionally out website is supported and developed by separate teams (marketing, ux/ui designers, front-end developers). This repository contains the source code of our project, so such issue is a little bit off-topic here. Such things can be discussed on our official [Gitter channel](https://gitter.im/exonum/exonum).

**Comment by lazaridiscom** [comment]
Actually our visions (yours and mine) are not that relevant here.

As for Gitter... No way. I've moved the issue over to the doc-project.

My apologies for the non-relevant traffic.
