### ISSUE TITLE
exonum compile error on keys.rs

### ISSUE THREAD

**Issue by lijamie98** [exonum/exonum#471]
There is a compile error at: 
https://github.com/exonum/exonum/blob/master/exonum/src/storage/keys.rs#L474

The trailing "," should be removed to avoid compile errors. 

rustc --version
rustc 1.21.0

cargo --version 
cargo 0.22.0

**Comment by lijamie98** [comment]
I will upgrade my rust version.
I also suggest to mention the rest version requirement in the installation guide or remove the trailing comma.

**Comment by slowli** [comment]
To be fair, [the installation guide](https://exonum.com/doc/get-started/install/) already specifies which Rust versions are supported:

> Exonum is tested against and is guaranteed to be compatible with the latest stable Rust toolchain, which can be obtained as specified above. [...] Older toolchains (for example, those that come with older Linux distributives) might cause Exonum compilation to fail, as Exonum uses some new language features. Please use rustup to install a compatible toolchain in this case.

I suppose the mentioned approximate lower bound of compatible versions (1.20) could be bumped to 1.23. If it's *only* the trailing comma that prevents the use of recent stable versions <1.23, I propose to remove it.

**Comment by DarkEld3r** [comment]
We have added the minimal required version in the root README.md. Feel free to reopen issue if you still have questions.
