### ISSUE TITLE
Help with generate public key and signature

### ISSUE THREAD

**Issue by voroncv** [exonum/exonum#554]
On this page - (https://exonum.com/doc/get-started/create-service/) you show how to create a service. In the end, you create 2 purses. How can I generate the same public key and signature? I will be grateful for the help!

**Comment by DarkEld3r** [comment]
Hello. 👋 

[Light client](https://github.com/exonum/exonum-client) can be used for that:
- https://github.com/exonum/exonum-client#generate-key-pair
- https://github.com/exonum/exonum-client#sign-data

Additionally, the same thing can be done using `exonum::crypto` [interface](https://docs.rs/exonum/0.6.0/exonum/crypto/index.html).

**Comment by DarkEld3r** [comment]
Feel free to reopen the issue if you still have questions.
