### ISSUE TITLE
How to synchronous blocks data?

### ISSUE THREAD

**Issue by Ank1996** [exonum/exonum#559]
I modified demo config and compiled demo2.
I configed both of them same consensus_key.
`crypto::gen_keypair_from_seed(&Seed::new([1; 32]))`
And configed demo2
 `
let peer_address = "0.0.0.0:2001".parse().unwrap();
NodeConfig{
...
peers: vec!["0.0.0.0:2000".parse().unwrap()],
...
}`

Default demo's peer_address is 0.0.0.0:2000.
I think while demo2 running, some connecttion build.
But after I tested wallet creating and tranfering, default demo's web api could should data, but demo2's web api showed nothing.

I'm not sure whether I have some misunderstanding. I want to know corret way to build a full node network.

**Comment by DarkEld3r** [comment]
Hello. 👋 

Could you please clarify what demo you are trying to use?
In case you are having troubles with setting up several exonum nodes, you can check [this](https://github.com/exonum/exonum/blob/master/services/configuration/doc/testnet-api-tutorial.md) tutorial.

Please add more details and I will gladly to help you.

**Comment by DarkEld3r** [comment]
Feel free to reopen the issue if you still have questions.
