### ISSUE TITLE
String constants for command line parameters [ECR-1234]

### ISSUE THREAD

**Issue by DarkEld3r** [exonum/exonum#616]
There are many string constants in the `/exonum/exonum/src/helpers/fabric/details.rs` module. They should be extracted into `const` similar to `DATABASE_PATH` and `OUTPUT_DIR`. See [sources](https://github.com/exonum/exonum/blob/master/exonum/src/helpers/fabric/details.rs#L40) for the details.

**Comment by popzxc** [comment]
Not actual anymore
