### ISSUE TITLE
Update `tokio-retry` and `tokio-timer` to 0.2+ version [ECR-1226]

### ISSUE THREAD

**Issue by DarkEld3r** [exonum/exonum#623]
Currently we are using `0.1._` versions of these crates. The update will require some changes because `0.2` versions Aren't compatible with the previous ones.

**Comment by alekseysidorov** [comment]
It seems that this task is already done
https://crates.io/crates/tokio-retry

**Comment by DarkEld3r** [comment]
@alekseysidorov 
[As far as I can see](https://github.com/exonum/exonum/blob/master/exonum/Cargo.toml#L47), we are still using `0.1.1` and `0.1.2` versions.

**Comment by alekseysidorov** [comment]
Sorry I am so tired and stupid
