### ISSUE TITLE
Node should panic if public or private api addresses are used [ECR-1003]

### ISSUE THREAD

**Issue by DarkEld3r** [exonum/exonum#626]
Currently node starts normally if only one of addresses is used. This behavior should be changed: node should panic with a meaningful error message.

**Comment by ivan-ochc** [comment]
This issue has already fixed. Node will panic if addresses are used:
"Unable to receive actix api system address for api: listen_addr 0.0.0.0:8091, scope private"
"Unable to receive actix api system address for api: listen_addr 0.0.0.0:8081, scope public"
