### ISSUE TITLE
Do not depend on configuration service in services [ECR-1147]

### ISSUE THREAD

**Issue by vitvakatu** [exonum/exonum#631]
`cryptocurrency-advanced` service depends on `exonum-configuration`, but doesn't use it internally, configuration service is used only in `main.rs` to start node. It makes sense to split `cryptocurrency-advanced` example into two crates - one for service library and one for the binary, and request `exonum-configuration` dependency only for latter one.

Moreover, other services and examples can also suffer from this issue.

**Comment by popzxc** [comment]
Not actual anymore.
