### ISSUE TITLE
Rename methods in `consensus.rs`

### ISSUE THREAD

**Issue by popzxc** [exonum/exonum#637]
Currently [consensus.rs](https://github.com/exonum/exonum/blob/master/exonum/src/node/consensus.rs) contains methods with non-intuitive names:

* `has_majority_prevotes`
* `has_majority_precommits`
* `has_full_propose`

It will be better to rename them to more consistent names, e.g. `handle_majority_prevotes`, `handle_majority_precommits`, `has_full_propose`.

**Comment by DarkEld3r** [comment]
Closed by #655.
