### ISSUE TITLE
Fix bail message in `State::add_propose` method

### ISSUE THREAD

**Issue by popzxc** [exonum/exonum#650]
Currently [state.rs](https://github.com/exonum/exonum/blob/master/exonum/src/node/state.rs) contains following code:

```
if transactions.contains(hash) && 
    !transaction_pool.contains(hash) {
    bail!(
        "Received propose with already\
         committed transaction"
    )
}
```

If it gets executed, it produces line "Received propose with alreadycommitted transaction".
Additional space should be added.

**Comment by DarkEld3r** [comment]
Closed by #650.
