### ISSUE TITLE
Make BaseIndex private

### ISSUE THREAD

**Issue by DarkEld3r** [exonum/exonum#687]
`BaseIndex` can be used for adding new index types, but because of new runtime checks that take into account [a fixed number of indexes](https://github.com/exonum/exonum/blob/master/exonum/src/storage/indexes_metadata.rs#L36) it is no longer possible.

Therefore, `BaseIndex` should be made private. All mentions in the documentation should be removed too.

**Comment by ivan-ochc** [comment]
Done in https://github.com/exonum/exonum/pull/723
