### ISSUE TITLE
multiple types

### ISSUE THREAD

**Issue by akosenkov** [exonum/exonum#698]
Hi guys, great project!

I'm just starting with Exonum and I was curious what is a go-to method to have multiple types inside of one service?

For example I have 
```
    encoding_struct! {
        struct Delegate {
            issuer: &PublicKey,
            expiry: &str,
            description: &str,
            resolution: &PublicKey,
        }
    }

    encoding_struct! {
        struct Promise {
            issuer: &PublicKey,
            expiry: &str,
            description: &str,
        }
    }

```
(and maybe struct Wallet as well)

And I want objects of both types to coexist - "delegate" objects having foreign keys pointing to "promise" objects.

How would I formulate that within the framework?
E.g. multiple services somehow interlinked? Or can it be done within a single one having two MapIndex?

Thank you!

**Comment by DarkEld3r** [comment]
Hello, thank you!

You are right: it can be done in one service using two (or more) map indexes, but you cannot reference one structure from another directly. You must use some key to identify related structures.

For example, hash of one of the structures can be used to identify the second one. Another possible solution is to have something like that:
```rust
MapIndex<PublicKey, Delegate> delegates;
MapIndex<PublicKey, Promise> promises;
```
Where `PublicKey` is an issuer public key.

**Comment by vitvakatu** [comment]
Closing now due to lack of response for a long time.
