### ISSUE TITLE
public/private key type

### ISSUE THREAD

**Issue by akosenkov** [exonum/exonum#699]
Hey guys!

I would like to use generated on Ethereum private/public keys with my Exonum blockchain and was wondering on how to achieve that...

Thank you very much!

**Comment by DarkEld3r** [comment]
Unfortunately, Ethereum and Exonum use different cryptographies which aren't compatible. Currently Exonum doesn't provide a simple solution for switching to other cryptography (you can modify the `exonum::crypto` module though).

In case you simply want to store Ethereum public key - it can be done (as raw bytes). :upside_down_face:

**Comment by vitvakatu** [comment]
Closing now due to lack of response for a long time.
