### ISSUE TITLE
Transaction hung as "in-pool" [ECR-1716]

### ISSUE THREAD

**Issue by avacom** [exonum/exonum#742]
Exonum: 0.8.0
rustc: 1.25.0

Infrastructure: 4 validtors + 1 auditor

1. Launch 1 auditor (4 validators are offline) - the simulation of the situation when the auditor node is offline towards the validator network
2. Post the transaction to the auditor
3. Check the transaction type - "in-pool"
4. Launch 4 validators - the simulation of the situation when the auditor goes online

**Expected:** the "in-pool" transaction is validated by the blockchain, and it is committed
**Actual:** the transaction remains "in-pool"; validators do not have any information about it

**Comment by DarkEld3r** [comment]
Thank you for the report. Currently auditors cannot resend transactions which is definitely a bug.

**Comment by avacom** [comment]
@DarkEld3r, thank you! Looking forward for the fix :)

**Comment by DarkEld3r** [comment]
As a quick and dirty solution we have added `v1/rebroadcas` endpoint (see #859 for details). A more sophisticated solution will be available in the future.

@avacom Feel free to reopen the issue if you have more questions.
