### ISSUE TITLE
websocket api endpoints

### ISSUE THREAD

**Issue by zakum1** [exonum/exonum#782]
In my application, I would like to have a light data streaming capability for clients to receive messages from the node.

With the change from iron to actix, this may be quite easy, because actix has websocket support. I would be prepared to contribute an implementation if the idea is accepted by the maintainers.

My basic thought is to create a function ServiceApiScope.endpoint_ws (complementary to the current ServiceApiScope.endpoint and ServiceApiScope.endpoint_mut). This function would allow services to register a handler for a websocket.

**Comment by vitvakatu** [comment]
Thank you for your feature request, @zakum1 
We'll discuss this proposal as soon as possible and I'll keep you in touch.

**Comment by popzxc** [comment]
It is now possible to create websocket endpoints, and Exonum already supports some websocket interaction (sending transactions, receiving notifications about events), see [example](https://github.com/exonum/exonum/blob/master/services/explorer/src/api/websocket/glue.rs) at explorer service.
