### ISSUE TITLE
Test time-independent consensus algorithm in denial scenarios 5/1 and 6/2 (no txs load). 

### ISSUE THREAD

**Issue by gisochre** [exonum/exonum#80]
`propose_timeout=500` in all cases. These are empty blocks.
1. For 
  - `6` and `8` nodes
  - `round_timeout = 3000`
  - `status_timeout = 5000`
performance is poor. Many (1-6) rounds per an empty block. 

 5-12 blocks per minute on 6 nodes. 

2. For
  - `6` and `8` nodes
  - `round_timeout = 3000`
  - `status_timeout = 3000` 

 74 blocks per minute on 6 nodes. 

3. For 
  - `5/1` and `6/2` nodes (`5/1` means `6` validators total, `1` stopped for maintenance or due to denial). 
  - `round_timeout = 3000`
  - `status_timeout = 1000`
No data. 

This is related to https://github.com/exonum/exonum-core/issues/2 and https://github.com/exonum/exonum-core/pull/29.

**Comment by Alexey-Architect** [comment]
This is not a issues

**Comment by gisochre** [comment]
Yeap, just close it.

**Comment by gisochre** [comment]
with `round_timeout = 1000` 
8/8: 95
7/8: 79
6/8: 57
5/8: halt. 

9/9: 92
8/9: 81
7/9: 62
