### ISSUE TITLE
Desync between explorer and chain state

### ISSUE THREAD

**Issue by mihalicyn** [exonum/exonum#809]
Hi all!

I meet interesting problem when using exonum-client - sometimes when I sent frequent transactions to chain I've got strange fails (unhandled promise rejection). After I've dived into the code I realised that in https://github.com/exonum/exonum-client/blob/e786962828bd523c178143dff03b7f5ff61350df/src/blockchain/transport.js#L64 no checked case when request to explorer failed (transactions explorer in exonum 0.8.1 returns 404). Then I checked that transactions that I'd sent to server appeared in explorer with delay.

Question is... it's bug or planned behaviour of explorer? If it's normal for explorer to have some delay and return 404 about applyed transaction -> we need to fix client; if it's not normal for explorer -> we need fix exonum.

As temp workaround for users: you can path exonum-client and add retry request to explorer.

Exonum 0.8.1

Thanks.

**Comment by vitvakatu** [comment]
@mihalicyn Hello. 
It would be super-great if you can provide some steps-to-reproduce, or maybe even some example application which shows described behavior.

First of all, are you using `0.8.1` version from crates.io or from Github directly? 

Right now I'm not sure what can cause described behavior, so I'm marking this issue as a bug. Thank you for your report, we'll definitely find what's going on.

**Comment by boguslavsky** [comment]
This behavior is now fixed in light-client. See new implementation:
https://github.com/exonum/exonum-client/blob/master/src/blockchain/transport.js#L78-L94
