### ISSUE TITLE
Documentaion unavailable

### ISSUE THREAD

**Issue by mrLSD** [exonum/exonum#863]
When I try to access **Exonum** documentation I have got error:

> The requested resource does not exist

Link: https://docs.rs/exonum/0.9.1/exonum/

Documentation link present at github README and Cargo.

**Comment by ilammy** [comment]
Unfortunately, docs.rs currently fails to build the docs due to an older nightly compiler version (see onur/docs.rs#225, onur/docs.rs#226).

**Comment by aleksuss** [comment]
Docs for a current version of exonum is already available https://docs.rs/exonum/0.10.3/exonum/
