### ISSUE TITLE
CryptoPro JCP

### ISSUE THREAD

**Issue by TFOMS** [exonum/exonum#875]
Hi ! 
How can I  integrate CryptoPro JCP in Exonum ?

**Comment by vitvakatu** [comment]
Hello. Sorry for a late response.
Your question is not a simple one, you can't do it without some internal changes in our codebase. You need to fork Exonum and implement your own cryptographic module, like [`sodiumoxide` implementation](https://github.com/exonum/exonum/tree/master/exonum/src/crypto/crypto_lib) provided by default.
Unfortunately it seems like not the simplest task even for a experienced Rust developer.

Also you may take a look at `exonum-java-binding` project. Perhaps, implementing required support would be much easier for you using Java than Rust.

Moreover, if you need a GOST-compatible cryptographic module and don't want to implement your own - you may contact `exonum@bitfury.com` - we provide GOST-compatible cryptographic algorithms for our clients.

**Comment by vitvakatu** [comment]
Closing now due to lack of response for a long time. We do not have any plans to implement support for CryptoPro JCP.
