### ISSUE TITLE
unable to compile under linux

### ISSUE THREAD

**Issue by bindt** [exonum/exonum#915]
hi,

compilation is aborted with errors.  

Linux  4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

cargo 0.26.0 (41480f5cc 2018-02-26)
rustup 1.13.0 (ea9259c1b 2018-07-16)

cargo test --manifest-path exonum/Cargo.toml

warning: unused manifest key: package.autobenches
   Compiling subtle v0.6.3
   Compiling crossbeam-utils v0.3.2
   Compiling crossbeam-utils v0.2.2
   Compiling log v0.4.4
   Compiling exonum v0.9.0 (file:///work/BChain/exonum-master/exonum)
   Compiling kernel32-sys v0.2.2
   Compiling dbghelp-sys v0.2.0
   Compiling serde v1.0.75
   Compiling rayon-core v1.4.1
   Compiling synom v0.11.3
   Compiling bit-set v0.5.0
error[E0658]: 128-bit type is unstable (see issue #35118)
   --> /home/x0x/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-0.6.3/src/lib.rs:245:25
    |
245 | generate_integer_equal!(u128, i128, 128);
    |                         ^^^^

error[E0658]: 128-bit type is unstable (see issue #35118)
   --> /home/x0x/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-0.6.3/src/lib.rs:245:31
    |
245 | generate_integer_equal!(u128, i128, 128);
    |                               ^^^^

error[E0658]: 128-bit type is unstable (see issue #35118)
   --> /home/x0x/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-0.6.3/src/lib.rs:323:38
    |
323 | generate_integer_conditional_assign!(u128 i128);
    |                                      ^^^^

error[E0658]: 128-bit type is unstable (see issue #35118)
   --> /home/x0x/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-0.6.3/src/lib.rs:286:9
    |
286 |         i128
    |         ^^^^
...
323 | generate_integer_conditional_assign!(u128 i128);
    | ------------------------------------------------ in this macro invocation

error[E0658]: 128-bit type is unstable (see issue #35118)
   --> /home/x0x/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-0.6.3/src/lib.rs:323:43
    |
323 | generate_integer_conditional_assign!(u128 i128);
    |                                           ^^^^

error[E0658]: 128-bit type is unstable (see issue #35118)
   --> /home/x0x/.cargo/registry/src/github.com-1ecc6299db9ec823/subtle-0.6.3/src/lib.rs:301:9
    |
301 |         i128
    |         ^^^^
...
323 | generate_integer_conditional_assign!(u128 i128);
    | ------------------------------------------------ in this macro invocation

error: aborting due to 6 previous errors

error: Could not compile `subtle`.
warning: build failed, waiting for other jobs to finish...
error: build failed

cheers

**Comment by bindt** [comment]
tnx for hint.

confirmed. looks like some broken installation, despite it is latest compiler version 1.28 the error was reported.  reinstall resolved issues.

**Comment by vitvakatu** [comment]
Great! Feel free to ask any questions her or on our [Gitter](https://gitter.im/exonum/exonum)
