### ISSUE TITLE
DB size concern

### ISSUE THREAD

**Issue by avacom** [exonum/exonum#931]
exonum: 0.9.1
rustc: 1.28.0

Test system:
- OS: Linux
- Uptime: 3 days
- Transaction producing:
1. Node 1: 1 trx every 1 min
2. Node 2: 1 trx every 1 min
3. Node 3: 1 trx every 2 min

At the end of the test period, a single DB size was 3.4 GB. We performed a restart. The size was dropped to 850 MB

Question 1: Is 3.4 GB a normal DB size taking into account the mentioned configuration?
Question 2: Is it normal that the size is decreased so much after the restart?

**Comment by aleksuss** [comment]
Answer 1: DB size depends on two moments. 1. A frequency of block generation. 2. A size of transactions. 
Answer 2: Yes, it is. Because when node stops then binary journal deletes.

**Comment by avacom** [comment]
@aleksuss, thank you for a quick reply. Is it possible to force this journal cleanup during the runtime?

**Comment by aleksuss** [comment]
@avacom you are welcome. Actually it is internal logic of `rocksdb`. I mean a managing of WAL journal. In current exonum configuration we use default settings for this. To read how it works you can here https://github.com/facebook/rocksdb/wiki/Write-Ahead-Log

**Comment by avacom** [comment]
@aleksuss, thank you for the explanation. Case is closed :)
