### ISSUE TITLE
Inconsistency in deserialization of large integers

### ISSUE THREAD

**Issue by blackbeam** [exonum/exonum#999]
Hi.

I've just ran into an inconsistency in deserialization of large integers between this code:

https://github.com/exonum/exonum/blob/a4cb49c27b7a39ef933930b8c4aa8a1a2e2dde10/exonum/src/encoding/serialize/json.rs#L118-L121

and this code:

https://github.com/exonum/exonum/blob/a4cb49c27b7a39ef933930b8c4aa8a1a2e2dde10/exonum/src/encoding/serialize/json.rs#L38-L39

As a result this will work:

<details>
  <summary>Click to show code</summary>

```rust
encoding_struct! (
    struct Foo {
        foo: u64, // << plain u64
    }
);

let mut buffer = vec![0; Foo::field_size() as usize];
let from: Offset = 0;
let to: Offset = Foo::field_size();
let checked_from = CheckedOffset::new(from);
let checked_to = CheckedOffset::new(to);

let foo1 = Foo::new(vec![42]);

let serialized = foo1.serialize_field().unwrap();
Foo::deserialize_field(&serialized, &mut buffer, from, to).unwrap();
Foo::check(&buffer, checked_from, checked_to, checked_to).unwrap();
let foo = unsafe { Foo::read(&buffer, from, to) };
assert_eq!(foo1, foo);
```

</details>
<br/>
But this won't:

<br/>
<details>
  <summary>Click to show code</summary>

```rust
encoding_struct!(
    struct Foo {
        bar: Vec<u64>, // << u64 wrapped in a segment field
    }
);

let mut buffer = vec![0; Foo::field_size() as usize];
let from: Offset = 0;
let to: Offset = Foo::field_size();
let checked_from = CheckedOffset::new(from);
let checked_to = CheckedOffset::new(to);

let foo1 = Foo::new(vec![42]);

let serialized = foo1.serialize_field().unwrap();
Foo::deserialize_field(&serialized, &mut buffer, from, to).unwrap();
// ^^ called `Result::unwrap()` on an `Err` value: Error("invalid type: string \"42\", expected u64", line: 0, column: 0)

Foo::check(&buffer, checked_from, checked_to, checked_to).unwrap();
let foo = unsafe { Foo::read(&buffer, from, to) };
assert_eq!(foo1, foo);
```

</details>

**Comment by vldm** [comment]
@blackbeam Thank you for your issue.

Looks like we're depend on old serde deserialisation. (Before 1.0 serde implement deserialisation of integers from Value::String https://github.com/serde-rs/json/issues/317)

In future we are going to remove our encoding and use protobuf. https://exonum.com/doc/roadmap/ 

I am going to look on this more closely, if i found some fast-fix, then we can release bugfix version.

**Comment by dvush** [comment]
As it was mentioned before we use protobuf for encoding now.
